name: Fumotoppara Checker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:       # 手動実行も可能

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore notified cache
        uses: actions/cache@v4
        with:
          path: |
            .notified_cache
          key: notified-cache-${{ github.run_id }}
          restore-keys: |
            notified-cache-

      - name: Install dependencies
        run: npm install puppeteer node-fetch

      - name: Run script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: node index.js

      - name: Save updated cache
        if: always()
        run: |
          mkdir -p .notified_cache
          cp notified_cache.json .notified_cache/notified_cache.json
